<a href="https://colab.research.google.com/github/korkutanapa/DCASE2025_TASK2/blob/main/ORJ_DCASE_EVALUATOR_GROUNDTRUTH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!rm -rf /content/*

In [52]:
# ============================================================
# 1) INSTALL / CLONE OFFICIAL DCASE 2025 TASK 2 EVALUATOR
# ============================================================

%cd /content

!rm -rf dcase2025_task2_evaluator
!git clone https://github.com/nttcslab/dcase2025_task2_evaluator.git

%cd /content/dcase2025_task2_evaluator

/content
Cloning into 'dcase2025_task2_evaluator'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 65 (delta 35), reused 65 (delta 35), pack-reused 0 (from 0)
Receiving objects: 100% (65/65), 256.63 KiB | 8.85 MiB/s, done.
Resolving deltas: 100% (35/35), done.
/content/dcase2025_task2_evaluator


In [53]:
# ============================================================
# 2) CREATE REQUIRED FOLDER STRUCTURE
# ============================================================

import os
import pandas as pd
import numpy as np

TEAM_NAME = "METU"
SYSTEM_NAME = "TDA"

BASE_DIR = "/content/dcase2025_task2_evaluator"
OUTPUT_DIR = f"{BASE_DIR}/teams/{TEAM_NAME}/{SYSTEM_NAME}"

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Output folder:")
print(OUTPUT_DIR)

Output folder:
/content/dcase2025_task2_evaluator/teams/METU/TDA


In [54]:
import os
import glob
import pandas as pd
from IPython.display import display

In [55]:
# ============================================================
# 0. REQUIRED IMPORTS
# ============================================================

import os
import glob
import pandas as pd
from IPython.display import display


# ============================================================
# 5. RUN OFFICIAL EVALUATOR
# ============================================================

!python dcase2025_task2_evaluator.py \
    --teams_root_dir ./teams \
    --result_dir ./teams_result \
    --additional_result_dir ./teams_additional_result \
    --dir_depth 2 \
    --out_all True


# ============================================================
# 6. LIST CREATED OUTPUT FILES
# ============================================================

print("\n================ OFFICIAL EVALUATOR OUTPUT FILES ================")

print("\nFiles in teams_result:")
for f in sorted(glob.glob("./teams_result/*.csv")):
    print(f)

print("\nFiles in teams_additional_result:")
for f in sorted(glob.glob("./teams_additional_result/*.csv")):
    print(f)

print("\nFiles in teams_additional_result/TDA:")
for f in sorted(glob.glob("./teams_additional_result/TDA/*.csv")):
    print(f)


# ============================================================
# 7. READ TDA_result.csv SAFELY AS RAW TEXT
# ============================================================
# Do NOT use pd.read_csv() for this file.
# It has a mixed/non-rectangular structure.

main_result_file = "./teams_result/TDA_result.csv"

print("\n================ RAW TDA_result.csv ================")

if os.path.exists(main_result_file):
    with open(main_result_file, "r") as f:
        print(f.read())
else:
    print("TDA_result.csv was not created.")
    print("Check whether the evaluator found ./teams/METU/TDA correctly.")


# ============================================================
# 8. READ OFFICIAL SCORE FILES CORRECTLY
# ============================================================

official_score_file = "./teams_additional_result/teams_official_score.csv"
official_score_paper_file = "./teams_additional_result/teams_official_score_paper.csv"
section_auc_file = "./teams_additional_result/teams_section_00_auc.csv"
section_score_file = "./teams_additional_result/teams_section_00_score.csv"
system_official_score_file = "./teams_additional_result/TDA/official_score.csv"

print("\n================ teams_official_score.csv ================")

if os.path.exists(official_score_file):
    official_df = pd.read_csv(official_score_file)
    display(official_df)
else:
    print("teams_official_score.csv was not created.")

print("\n================ teams_official_score_paper.csv ================")

if os.path.exists(official_score_paper_file):
    paper_df = pd.read_csv(official_score_paper_file)
    display(paper_df)
else:
    print("teams_official_score_paper.csv was not created.")

print("\n================ teams_section_00_auc.csv ================")

if os.path.exists(section_auc_file):
    section_auc_df = pd.read_csv(section_auc_file)
    display(section_auc_df)
else:
    print("teams_section_00_auc.csv was not created.")

print("\n================ teams_section_00_score.csv ================")

if os.path.exists(section_score_file):
    section_score_df = pd.read_csv(section_score_file)
    display(section_score_df)
else:
    print("teams_section_00_score.csv was not created.")

print("\n================ TDA/official_score.csv ================")

if os.path.exists(system_official_score_file):
    system_score_df = pd.read_csv(system_official_score_file)
    display(system_score_df)
else:
    print("TDA/official_score.csv was not created.")


# ============================================================
# 9. FINAL SHORT SUMMARY
# ============================================================

print("\n================ FINAL SUMMARY ================")

if os.path.exists(official_score_file):
    print("Official evaluator completed successfully.")
    print("Main official result file:")
    print(os.path.abspath(official_score_file))
else:
    print("Official evaluator did not create the expected official score file.")

[1/1] team name : TDA
./teams/METU/TDA
[1/8] machine type : AutoTrash
section_00
normal : 100 files
anomaly : 100 files
source : 100 files
target : 100 files
export fig -> ./teams_additional_result/TDA//TDA_AutoTrash_section_00_anm_score.png
[2/8] machine type : BandSealer
section_00
normal : 100 files
anomaly : 100 files
source : 100 files
target : 100 files
export fig -> ./teams_additional_result/TDA//TDA_BandSealer_section_00_anm_score.png
[3/8] machine type : CoffeeGrinder
section_00
normal : 100 files
anomaly : 100 files
source : 100 files
target : 100 files
export fig -> ./teams_additional_result/TDA//TDA_CoffeeGrinder_section_00_anm_score.png
[4/8] machine type : HomeCamera
section_00
normal : 100 files
anomaly : 100 files
source : 100 files
target : 100 files
export fig -> ./teams_additional_result/TDA//TDA_HomeCamera_section_00_anm_score.png
[5/8] machine type : Polisher
section_00
normal : 100 files
anomaly : 100 files
source : 100 files
target : 100 files
export fig -> ./tea

,Unnamed: 0,official score,arithmetic mean,harmonic mean (source),harmonic mean (target),AutoTrash AUC (source),BandSealer AUC (source),CoffeeGrinder AUC (source),HomeCamera AUC (source),Polisher AUC (source),...,ToyPet AUC (source),ToyRCCar AUC (source),AutoTrash AUC (target),BandSealer AUC (target),CoffeeGrinder AUC (target),HomeCamera AUC (target),Polisher AUC (target),ScrewFeeder AUC (target),ToyPet AUC (target),ToyRCCar AUC (target)
0,TDA,0.654684,0.663412,0.662252,0.645808,0.7342,0.582,0.7314,0.7022,0.6356,...,0.603,0.6186,0.7662,0.5068,0.5896,0.629,0.5888,0.795,0.6728,0.7242



================ teams_official_score_paper.csv ================


,System,metric,h-mean,a-mean,AutoTrash,BandSealer,CoffeeGrinder,HomeCamera,Polisher,ScrewFeeder,ToyPet,ToyRCCar
0,TDA,AUC (source),0.662252,0.667775,0.734200,0.582000,0.731400,0.702200,0.635600,0.735200,0.603000,0.618600
1,TDA,AUC (target),0.645808,0.659050,0.766200,0.506800,0.589600,0.629000,0.588800,0.795000,0.672800,0.724200
2,TDA,"pAUC (source, target)",0.656205,0.659276,0.672632,0.578421,0.678947,0.673684,0.663158,0.744211,0.626316,0.636842
3,TDA,TOTAL score,0.654684,0.662034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN



================ teams_section_00_auc.csv ================


,Unnamed: 0,official score,arithmetic mean,harmonic mean (source),harmonic mean (target),AutoTrash AUC (source),BandSealer AUC (source),CoffeeGrinder AUC (source),HomeCamera AUC (source),Polisher AUC (source),...,ToyPet AUC (source),ToyRCCar AUC (source),AutoTrash AUC (target),BandSealer AUC (target),CoffeeGrinder AUC (target),HomeCamera AUC (target),Polisher AUC (target),ScrewFeeder AUC (target),ToyPet AUC (target),ToyRCCar AUC (target)
0,TDA,NaN,NaN,NaN,NaN,0.7342,0.582,0.7314,0.7022,0.6356,...,0.603,0.6186,0.7662,0.5068,0.5896,0.629,0.5888,0.795,0.6728,0.7242



================ teams_section_00_score.csv ================


,Unnamed: 0,official score,arithmetic mean,harmonic mean (source),harmonic mean (target),AutoTrash Score (source),BandSealer Score (source),CoffeeGrinder Score (source),HomeCamera Score (source),Polisher Score (source),...,ToyPet Score (source),ToyRCCar Score (source),AutoTrash Score (target),BandSealer Score (target),CoffeeGrinder Score (target),HomeCamera Score (target),Polisher Score (target),ScrewFeeder Score (target),ToyPet Score (target),ToyRCCar Score (target)
0,TDA,NaN,NaN,NaN,NaN,3.581285,-2.429237,-4.060808,3.14559,-3.010739,...,2.938823,3.633871,3.726772,-2.203887,-3.428097,3.304975,-2.890168,3.858075,2.799844,3.386527



================ TDA/official_score.csv ================


,Unnamed: 0,official score,arithmetic mean,harmonic mean (source),harmonic mean (target),AutoTrash AUC (source),BandSealer AUC (source),CoffeeGrinder AUC (source),HomeCamera AUC (source),Polisher AUC (source),...,ToyPet AUC (source),ToyRCCar AUC (source),AutoTrash AUC (target),BandSealer AUC (target),CoffeeGrinder AUC (target),HomeCamera AUC (target),Polisher AUC (target),ScrewFeeder AUC (target),ToyPet AUC (target),ToyRCCar AUC (target)
0,TDA,0.654684,0.663412,0.662252,0.645808,0.7342,0.582,0.7314,0.7022,0.6356,...,0.603,0.6186,0.7662,0.5068,0.5896,0.629,0.5888,0.795,0.6728,0.7242



================ FINAL SUMMARY ================
Official evaluator completed successfully.
Main official result file:
/content/dcase2025_task2_evaluator/teams_additional_result/teams_official_score.csv


In [56]:
import os
import pandas as pd
from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

EVAL_DIR = "/content/dcase2025_task2_evaluator"
PRED_DIR = "/content/dcase2025_task2_evaluator/teams/METU/TDA"

MACHINES = [
    "AutoTrash",
    "BandSealer",
    "CoffeeGrinder",
    "HomeCamera",
    "Polisher",
    "ScrewFeeder",
    "ToyPet",
    "ToyRCCar",
]

def read_no_header_csv(path, colname):
    df = pd.read_csv(path, header=None, names=["filename", colname])
    df["filename"] = df["filename"].astype(str)
    return df

for machine in MACHINES:
    print("\n" + "=" * 80)
    print(machine)
    print("=" * 80)

    gt_path = os.path.join(
        EVAL_DIR,
        "ground_truth_data",
        f"ground_truth_{machine}_section_00_test.csv"
    )

    domain_path = os.path.join(
        EVAL_DIR,
        "ground_truth_domain",
        f"ground_truth_{machine}_section_00_test.csv"
    )

    score_path = os.path.join(
        PRED_DIR,
        f"anomaly_score_{machine}_section_00_test.csv"
    )

    decision_path = os.path.join(
        PRED_DIR,
        f"decision_result_{machine}_section_00_test.csv"
    )

    gt = read_no_header_csv(gt_path, "y_true")
    domain = read_no_header_csv(domain_path, "domain")
    score = read_no_header_csv(score_path, "score")
    decision = read_no_header_csv(decision_path, "decision")

    df = (
        gt.merge(domain, on="filename", how="inner")
          .merge(score, on="filename", how="inner")
          .merge(decision, on="filename", how="inner")
    )

    print("Merged rows:", len(df))
    print("Ground truth rows:", len(gt))
    print("Score rows:", len(score))
    print("Decision rows:", len(decision))

    if len(df) != len(gt):
        print("WARNING: filename mismatch detected.")
        missing_pred = set(gt["filename"]) - set(score["filename"])
        extra_pred = set(score["filename"]) - set(gt["filename"])
        print("Missing prediction filenames:", list(sorted(missing_pred))[:10])
        print("Extra prediction filenames:", list(sorted(extra_pred))[:10])
        continue

    y_true = df["y_true"].astype(int).values
    y_score = df["score"].astype(float).values
    y_decision = df["decision"].astype(int).values

    print("\nALL FILES")
    print("AUC:", roc_auc_score(y_true, y_score))
    print(confusion_matrix(y_true, y_decision, labels=[0, 1]))

    for domain_name, domain_value in [("source", 0), ("target", 1)]:
        dfd = df[df["domain"].astype(int) == domain_value]

        y_true_d = dfd["y_true"].astype(int).values
        y_score_d = dfd["score"].astype(float).values
        y_decision_d = dfd["decision"].astype(int).values

        print(f"\n{domain_name.upper()} DECISION MATRIX")
        print("n:", len(dfd))
        print(confusion_matrix(y_true_d, y_decision_d, labels=[0, 1]))
        print("Accuracy:", accuracy_score(y_true_d, y_decision_d))
        print("Precision:", precision_score(y_true_d, y_decision_d, zero_division=0))
        print("Recall:", recall_score(y_true_d, y_decision_d, zero_division=0))
        print("F1:", f1_score(y_true_d, y_decision_d, zero_division=0))

    # Official-style domain AUC
    for domain_name, domain_value in [("source", 0), ("target", 1)]:
        mask_auc = (df["domain"].astype(int) == domain_value) | (df["y_true"].astype(int) != 0)

        y_true_auc = df.loc[mask_auc, "y_true"].astype(int).values
        y_score_auc = df.loc[mask_auc, "score"].astype(float).values

        print(f"\nOFFICIAL-STYLE {domain_name.upper()} AUC")
        print("n used:", len(y_true_auc))
        print("AUC:", roc_auc_score(y_true_auc, y_score_auc))


AutoTrash
Merged rows: 200
Ground truth rows: 200
Score rows: 200
Decision rows: 200

ALL FILES
AUC: 0.7502
[[63 37]
 [37 63]]

SOURCE DECISION MATRIX
n: 100
[[30 20]
 [ 9 41]]
Accuracy: 0.71
Precision: 0.6721311475409836
Recall: 0.82
F1: 0.7387387387387387

TARGET DECISION MATRIX
n: 100
[[33 17]
 [28 22]]
Accuracy: 0.55
Precision: 0.5641025641025641
Recall: 0.44
F1: 0.4943820224719101

OFFICIAL-STYLE SOURCE AUC
n used: 150
AUC: 0.7342

OFFICIAL-STYLE TARGET AUC
n used: 150
AUC: 0.7662

BandSealer
Merged rows: 200
Ground truth rows: 200
Score rows: 200
Decision rows: 200

ALL FILES
AUC: 0.5444000000000001
[[52 48]
 [48 52]]

SOURCE DECISION MATRIX
n: 100
[[29 21]
 [31 19]]
Accuracy: 0.48
Precision: 0.475
Recall: 0.38
F1: 0.4222222222222222

TARGET DECISION MATRIX
n: 100
[[23 27]
 [17 33]]
Accuracy: 0.56
Precision: 0.55
Recall: 0.66
F1: 0.6

OFFICIAL-STYLE SOURCE AUC
n used: 150
AUC: 0.582

OFFICIAL-STYLE TARGET AUC
n used: 150
AUC: 0.5068

CoffeeGrinder
Merged rows: 200
Ground truth r